#!/usr/bin/env python3
"""
把去冗余后的四类规则 (suffix/full/keyword/regexp) 渲染成:
  - Egern YAML  (egern/<category>.yaml)
  - Loon .list  (loon/<category>.list)

Egern YAML 格式约定（与 wot1026/egern、wot1026/rules 现有产物保持一致风格）:
  payload:
    - DOMAIN-SUFFIX,example.com
    - DOMAIN,full.example.com
    - DOMAIN-KEYWORD,keyword

Loon .list 格式:
  DOMAIN-SUFFIX,example.com
  DOMAIN,full.example.com
  DOMAIN-KEYWORD,keyword

注意: regexp 类型 Egern/Loon 均不原生支持，默认丢弃并在生成日志中报告数量，
避免规则文件里出现客户端无法解析的行。
"""
from __future__ import annotations


def render_egern(suffix, full, keyword, category: str) -> str:
    lines = ["payload:"]
    for d in full:
        lines.append(f"  - DOMAIN,{d}")
    for d in suffix:
        lines.append(f"  - DOMAIN-SUFFIX,{d}")
    for d in keyword:
        lines.append(f"  - DOMAIN-KEYWORD,{d}")
    header = (
        f"# category: {category}\n"
        f"# generated by geo-egern-rules, do not edit by hand\n"
    )
    return header + "\n".join(lines) + "\n"


def render_loon(suffix, full, keyword, category: str) -> str:
    lines = [f"# category: {category}", "# generated by geo-egern-rules, do not edit by hand"]
    for d in full:
        lines.append(f"DOMAIN,{d}")
    for d in suffix:
        lines.append(f"DOMAIN-SUFFIX,{d}")
    for d in keyword:
        lines.append(f"DOMAIN-KEYWORD,{d}")
    return "\n".join(lines) + "\n"
